kustomize/jupyter-web-app/base/config-map.yaml
I added the geomatics version as Christian's team will be using it. Blair will look into whether or not geomatics-notebook-cpu will still be necessary.
=> feat(notebook): Update ml-workspace in config-map

kustomize/jupyter-web-app/base/config-map.yaml
Resolves https://github.com/StatCan/daaas/issues/114
Keeps the same version of the image from 17 days ago. I will update the version after certain PRs can be sorted out.
=> feat(notebook): rename ml-workspace to remote-desktop

kustomize/jupyter-web-app/base/kustomization.yaml
https://github.com/StatCan/kubeflow/commit/71d86067fd0ed0721d1eaa84419f44e40b90e79e
=> fix(jupyter): restore correct gpu, pvc options

kustomize/jupyter-web-app/base/config-map.yaml
Resolves https://github.com/StatCan/kubeflow-containers-desktop/issues/16
=> feat(notebook): update r-studio-cpu

kustomize/jupyter-web-app/base/config-map.yaml
- Fixes in-browser VS Code
- Landing page (Resolves https://github.com/StatCan/kubeflow-containers/issues/38)
=> feat(notebook): update remote-desktop

kustomize/jupyter-web-app/base/kustomization.yaml
New tag: 2e9daf661793db54fddc1e22ad04746a90b4957d
=> chore: Update jupyter-apis image

kustomize/jupyter-web-app/base/deployment.yaml, kustomize/jupyter-web-app/base/params.env
Resolves https://github.com/StatCan/kubeflow-manifest/issues/50
=> fix: add KUBECOST_URL to jupyter-web-app deployment

kustomize/jupyter-web-app/base/config-map.yaml, kustomize/jupyter-web-app/base/kustomization.yaml
Resolves https://github.com/StatCan/kubeflow-manifest/issues/43
=> chore: update image commits

kustomize/centraldashboard/base/kustomization.yaml
New tag: 8fdce6ddcc1bd87e20454b04078486a41956a82f
=> chore: Update centraldashboard image

kustomize/knative-install/base/deployment.yaml
This may introduce a problem with Knative Serving down the road
=> fix(knative): Remove istio injection for Knative Serving

kustomize/centraldashboard/base/deployment.yaml, kustomize/centraldashboard/base/kustomization.yaml
This reverts commit 45cec8eb55ad9b416a9c9282173773a2b6804187.
This reverts commit 8a0ce3344b1d3445aa7477c872d2eeee377c6a6f.
=> revert: Bad centraldashboard deployment

kustomize/jupyter-web-app/base/configs/spawner_ui_config.yaml
Hey @zachomedia does this look good?
Is the new generated list of @blairdrummond containers.
=> feat(jupyter): Update list of containers

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml
I borked the rebase so just made a new branch.
CC @wg102
=> feat(spawner-ui): update image list

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml, kustomize/application/jupyter-web-app/deployment.yaml
new tag: 2c1532b00791fce51d926d3a31a9f528179f7e72
=> chore: update jupyter-apis image and set shm false

kustomize/application/centraldashboard/deployment.yaml, kustomize/application/centraldashboard/links-configmap.yaml
Closes: https://github.com/StatCan/kubeflow-manifest/issues/81
Closes: https://github.com/StatCan/kubeflow/issues/40
=> feat(centraldashboard): Add i18n to links configmap

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml
new tag fc37cc9b41cf8b7f7b7bcbef9a48927c346fe5e9
https://github.com/StatCan/kubeflow-containers-desktop/commit/fc37cc9b41cf8b7f7b7bcbef9a48927c346fe5e9
=> chore: update remote-desktop image

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml
https://github.com/StatCan/kubeflow-containers/pull/220 must be merged first before this one
=> feat: update kf-containers to dee04931

kustomize/application/jupyter-web-app/deployment.yaml
Need to merge this PR to show changes in https://github.com/StatCan/jupyter-apis/pull/60
for issue: https://github.com/StatCan/daaas/issues/358
=> Update jupyter-apis image

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml
Resolves #94 
using SHA 3c7dcfb5
=> update jupyterlab image

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml
=> Update jupyterlab images

kustomize/application/jupyter-web-app/configs/spawner_ui_config.yaml
Close: StatCan/kubeflow-containers/issues/256
PR: StatCan/kubeflow-containers/pull/264
=> update: image SHA tags

kustomize/common/kubeflow-namespace/base/kustomization.yaml, kustomize/common/kubeflow-namespace/base/namespace_patch.json
=> feat(component): Add common component kubeflow-namespace

kustomize/apps/katib/base/kustomization.yaml, kustomize/apps/kfserving/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/argo/kubeflow.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component katib

kustomize/apps/profiles/base/deployment.yaml, kustomize/apps/profiles/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component profiles

kustomize/apps/notebook-controller/base/deployment.yaml, kustomize/apps/notebook-controller/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component notebook-controller

kustomize/apps/pytorch-job/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component pytorch-job

kustomize/apps/tf-training/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component tf-training

kustomize/apps/mpi-job/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component mpi-job

kustomize/contrib/spark/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add contrib component spark

kustomize/apps/mxnet-job/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add apps component mxnet-job

kustomize/contrib/seldon/base/kustomization.yaml, kustomize/stacks/aaw/kustomization.yaml, kustomize/stacks/local/kustomization.yaml, kustomize/stacks/upstream/kustomization.yaml
=> feat(component): Add contrib component seldon

kustomize/apps/jupyter-web-app/base/cluster-role.yaml, kustomize/apps/jupyter-web-app/base/configs/spawner_ui_config.yaml, kustomize/apps/jupyter-web-app/base/deployment.yaml
Signed-off-by: sylus <sylus1984@gmail.com>
=> feat(jupyter): Update Jupyter Config

kustomize/apps/pipeline/base/sync.py
Closes https://github.com/StatCan/jupyter-apis/issues/104
=> feat(i18n):i18n kfp desc

kustomize/apps/jupyter-web-app/base/configs/spawner_ui_config.yaml
Update spawner_config.
Related to https://github.com/StatCan/jupyter-apis/issues/109
=> fix: image icon

kustomize/apps/centraldashboard/base/centraldashboard-config.yaml
As per our discussion from our tech elab, decided to remove Katib from UI.
Closes https://github.com/StatCan/jupyter-apis/issues/114
=> fix(katib): Remove katib from UI

kustomize/apps/jupyter-web-app/base/deployment.yaml
Update to latest image from : https://github.com/StatCan/jupyter-apis/runs/5516918765?check_suite_focus=true
=> Update deployment to new jupyter-api image
